pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Python Test') {
            steps {
                sh '''
                    python3 --version
                    python3 -m py_compile python-app/app.py
                '''
            }
        }

        stage('Checkov Terraform Scan') {
            steps {
                sh '''
                    export PATH="$HOME/.local/bin:$PATH"
                    checkov -f terraform1/main.tf
                '''
            }
        }

        stage('Docker Build') {
            steps {
                sh '''
                    cd python-app
                    docker build -t devops-python-app:${BUILD_NUMBER} .
                '''
            }
        }

        stage('Trivy Scan') {
            steps {
                sh '''
                    trivy image \
                    --severity HIGH,CRITICAL \
                    --exit-code 1 \
                    devops-python-app:${BUILD_NUMBER}
                '''
            }
        }
    }
}
