pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Python Test') {
            steps {
                dir('python-app') {
                    sh '''
                        python3 --version
                        python3 -m pip install -r requirements.txt
                        python3 -m py_compile app.py
                    '''
                }
            }
        }

        stage('Checkov Scan') {
            steps {
                sh '''
                    checkov -f terraform1/main.tf
                '''
            }
        }

        stage('Docker Build') {
            steps {
                dir('python-app') {
                    sh '''
                        docker build -t devops-python-app:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Trivy Scan') {
            steps {
                sh '''
                    trivy image \
                    --severity HIGH,CRITICAL \
                    --exit-code 1 \
                    devops-python-app:${BUILD_NUMBER}
                '''
            }
        }
    }
}
